"""empty message

Revision ID: 1d38e05fc7e0
Revises:
Create Date: 2021-05-27 12:29:03.974449

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "1d38e05fc7e0"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "location",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("name", sa.String(length=60), nullable=True),
        sa.Column("longitude", sa.Numeric(), nullable=True),
        sa.Column("latitude", sa.Numeric(), nullable=True),
        sa.Column("full_address", sa.String(), nullable=True),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "zone",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("name", sa.String(length=60), nullable=True),
        sa.Column("wave_points", sa.String(length=60), nullable=True),
        sa.Column("modified", sa.String(), nullable=False),
        sa.Column("created", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("wave_points"),
    )
    op.create_table(
        "zonelocation",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("zone_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("location_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("modified", sa.String(), nullable=False),
        sa.Column("created", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["location.id"],
        ),
        sa.ForeignKeyConstraint(
            ["zone_id"],
            ["zone.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("zonelocation")
    op.drop_table("zone")
    op.drop_table("location")
    # ### end Alembic commands ###
